VideoKlub2019/Controllers/FilmController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VideoKlub2019.Models;

namespace VideoKlub2019.Controllers
{
    public class FilmController : Controller
    {
        private readonly VideoKlubContext db;

        public FilmController(VideoKlubContext _db)
        {
            db = _db;
        }

        public FileContentResult CitajSliku(int? id)
        {
            if (id == null)
            {
                return null;
            }
            Film film = db.Filmovi.Find(id);

            if (film == null)
            {
                return null;
            }
            return File(film.Slika, film.SlikaTip);
        }

        [Authorize(Roles = "admin")]
        // GET: Film
        public async Task<IActionResult> Index()
        {
            var videoklub2019Context = db.Filmovi.Include(f => f.Zanr);
            return View(await videoklub2019Context.ToListAsync());
        }

        // GET: Film/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await db.Filmovi
                .Include(f => f.Zanr)
                .FirstOrDefaultAsync(m => m.FilmId == id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        [Authorize(Roles = "admin")]
        // GET: Film/Create
        public IActionResult Create()
        {
            ViewData["ZanrId"] = new SelectList(db.Zanrovi, "ZanrId", "NazivZanra");
            return View();
        }

        // POST: Film/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FilmId,Naziv,ZanrId,Reziser,Godina,Slika,SlikaTip,CenaPoDanu")] Film film, IFormFile odabranaSlika)
        {
            if (ModelState.IsValid)
            {
            using (MemoryStream ms = new MemoryStream())
            {
                await odabranaSlika.CopyToAsync(ms);
                film.Slika = ms.ToArray();
            }
            film.SlikaTip = odabranaSlika.ContentType;
            db.Add(film);
            await db.SaveChangesAsync();

             }
            ViewData["ZanrId"] = new SelectList(db.Zanrovi, "ZanrId", "NazivZanra", film.ZanrId);
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "admin")]
        // GET: Film/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await db.Filmovi.FindAsync(id);
            if (film == null)
            {
                return NotFound();
            }
            ViewData["ZanrId"] = new SelectList(db.Zanrovi, "ZanrId", "NazivZanra", film.ZanrId);
            return View(film);
        }

        // POST: Film/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FilmId,Naziv,ZanrId,Reziser,Godina,Slika,SlikaTip,CenaPoDanu")] Film film, IFormFile odabranaSlika, int promena = 0)
        {
            if (promena == 1 && odabranaSlika == null)
            {
                ModelState.AddModelError("Slika", "Niste odabrali sliku");
            }
            if (id != film.FilmId)
            {
                return NotFound();
            }
            Film fl = db.Filmovi.Find(film.FilmId);

            if (promena == 1)
            {
                using (MemoryStream ms = new MemoryStream())
                {
                    await odabranaSlika.CopyToAsync(ms);
                    fl.Slika = ms.ToArray();
                }
                fl.SlikaTip = odabranaSlika.ContentType;
            }
            fl.Naziv = film.Naziv;
            fl.ZanrId = film.ZanrId;
            fl.Reziser = film.Reziser;
            fl.Godina = film.Godina;
            fl.CenaPoDanu = film.CenaPoDanu;
            if (ModelState.IsValid)
            {
            try
            {
                db.Update(fl);
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!FilmExists(fl.FilmId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            }
            ViewData["ZanrId"] = new SelectList(db.Zanrovi, "ZanrId", "NazivZanra", film.ZanrId);
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "admin")]
        // GET: Film/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await db.Filmovi
                .Include(f => f.Zanr)
                .FirstOrDefaultAsync(m => m.FilmId == id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        // POST: Film/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var film = await db.Filmovi.FindAsync(id);
            db.Filmovi.Remove(film);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FilmExists(int id)
        {
            return db.Filmovi.Any(e => e.FilmId == id);
        }
    }
}

VideoKlub2019/Controllers/IznajmljivanjeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VideoKlub2019.Models;

namespace VideoKlub2019.Controllers
{
    public class IznajmljivanjeController : Controller
    {
        private readonly VideoKlubContext db;

        public IznajmljivanjeController(VideoKlubContext _db)
        {
            db = _db;
        }

        [Authorize(Roles = "admin")]
        // GET: Iznajmljivanje
        public async Task<IActionResult> Index()
        {
            var videoklub2019Context = db.Iznajmljivanja.Include(i => i.Film);
            return View(await videoklub2019Context.ToListAsync());
        }

        // GET: Iznajmljivanje/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var iznajmljivanje = await db.Iznajmljivanja
                .Include(i => i.Film)
                .FirstOrDefaultAsync(m => m.IznajmljivanjeId == id);
            if (iznajmljivanje == null)
            {
                return NotFound();
            }

            return View(iznajmljivanje);
        }

        [Authorize]
        // GET: Iznajmljivanje/Create
        public IActionResult Create()
        {
            ViewData["FilmId"] = new SelectList(db.Filmovi, "FilmId", "Naziv");
            return View();
        }

        // POST: Iznajmljivanje/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IznajmljivanjeId,FilmId,ClanId,DatumIznajmljivanja,DatumVracanja")] Iznajmljivanje iznajmljivanje)
        {
            if (ModelState.IsValid)
            {
                db.Add(iznajmljivanje);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FilmId"] = new SelectList(db.Filmovi, "FilmId", "Naziv", iznajmljivanje.FilmId);
            return View(iznajmljivanje);
        }

        [Authorize(Roles = "admin")]
        // GET: Iznajmljivanje/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var iznajmljivanje = await db.Iznajmljivanja.FindAsync(id);
            if (iznajmljivanje == null)
            {
                return NotFound();
            }
            ViewData["FilmId"] = new SelectList(db.Filmovi, "FilmId", "Naziv", iznajmljivanje.FilmId);
            return View(iznajmljivanje);
        }

        // POST: Iznajmljivanje/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IznajmljivanjeId,FilmId,ClanId,DatumIznajmljivanja,DatumVracanja")] Iznajmljivanje iznajmljivanje)
        {
            if (id != iznajmljivanje.IznajmljivanjeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(iznajmljivanje);
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IznajmljivanjeExists(iznajmljivanje.IznajmljivanjeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FilmId"] = new SelectList(db.Filmovi, "FilmId", "Naziv", iznajmljivanje.FilmId);
            return View(iznajmljivanje);
        }

        [Authorize(Roles = "admin")]
        // GET: Iznajmljivanje/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var iznajmljivanje = await db.Iznajmljivanja
                .Include(i => i.Film)
                .FirstOrDefaultAsync(m => m.IznajmljivanjeId == id);
            if (iznajmljivanje == null)
            {
                return NotFound();
            }

            return View(iznajmljivanje);
        }

        // POST: Iznajmljivanje/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var iznajmljivanje = await db.Iznajmljivanja.FindAsync(id);
            db.Iznajmljivanja.Remove(iznajmljivanje);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool IznajmljivanjeExists(int id)
        {
            return db.Iznajmljivanja.Any(e => e.IznajmljivanjeId == id);
        }
    }
}

VideoKlub2019/Controllers/KomentarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VideoKlub2019.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using VideoKlub2019.Data;

namespace VideoKlub2019.Controllers
{
    public class KomentarController : Controller
    {
        private readonly VideoKlubContext db;

        public KomentarController(VideoKlubContext _db)
        {
            db = _db;
        }

        // GET: Komentar
        public async Task<IActionResult> Index(int id=0)
        {
            ViewBag.Film = db.Filmovi.Where(f => f.FilmId == id);
            var videoKlubContext = db.Komentari.Where(k=>k.FilmId==id).Include(k => k.Film);
            return View(await videoKlubContext.ToListAsync());
        }

        // GET: Komentar/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var komentar = await db.Komentari
                .Include(k => k.Film)
                .FirstOrDefaultAsync(m => m.KomentarId == id);
            if (komentar == null)
            {
                return NotFound();
            }

            return View(komentar);
        }

        [Authorize]
        // GET: Komentar/Create
        public IActionResult Create(int id=0)
        {
            ViewBag.Id = id;
            ViewData["FilmId"] = new SelectList(db.Filmovi, "FilmId", "Naziv");
            return View();
        }

        // POST: Komentar/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("KomentarId,ClanId,Korisnik,Poruka,FilmId")] Komentar komentar)
        {
            if (ModelState.IsValid)
            {
                db.Add(komentar);
                await db.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            ViewData["FilmId"] = new SelectList(db.Filmovi, "FilmId", "Naziv", komentar.FilmId);
            return RedirectToAction("Index","Home");
        }
        [Authorize]
        // GET: Komentar/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var komentar = await db.Komentari.FindAsync(id);
            if (komentar == null)
            {
                return NotFound();
            }
            ViewData["FilmId"] = new SelectList(db.Filmovi, "FilmId", "Naziv", komentar.FilmId);
            return View(komentar);
        }
        [Authorize]
        // POST: Komentar/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("KomentarId,ClanId,Korisnik,Poruka,FilmId")] Komentar komentar)
        {

                if (id != komentar.KomentarId)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        db.Update(komentar);
                        await db.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!KomentarExists(komentar.KomentarId))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                ViewData["FilmId"] = new SelectList(db.Filmovi, "FilmId", "Naziv", komentar.FilmId);
                return View(komentar);
            
        }

        // GET: Komentar/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var komentar = await db.Komentari
                .Include(k => k.Film)
                .FirstOrDefaultAsync(m => m.KomentarId == id);
            if (komentar == null)
            {
                return NotFound();
            }

            return View(komentar);
        }

        // POST: Komentar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var komentar = await db.Komentari.FindAsync(id);
            db.Komentari.Remove(komentar);
            await db.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        private bool KomentarExists(int id)
        {
            return db.Komentari.Any(e => e.KomentarId == id);
        }
    }
}

VideoKlub2019/Views/Film/Create.cshtml
@model VideoKlub2019.Models.Film

@{
    ViewData["Title"] = "Create";
}

<h2>Unesite film:</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZanrId" class="control-label"></label>
                <select asp-for="ZanrId" class="form-control" asp-items="ViewBag.ZanrId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Reziser" class="control-label"></label>
                <input asp-for="Reziser" class="form-control" />
                <span asp-validation-for="Reziser" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Godina" class="control-label"></label>
                <input asp-for="Godina" class="form-control" />
                <span asp-validation-for="Godina" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="File1"></label>
                <input id="File1" type="file" name="odabranaSlika" accept=".jpg, .gif, .png" onchange="PrikaziSliku()" />
            </div>
            <div class="form-group">
                <img id="img1" src="" width="200" height="150" />
            </div>
            
            <div class="form-group">
                <label asp-for="CenaPoDanu" class="control-label"></label>
                <input asp-for="CenaPoDanu" class="form-control" />
                <span asp-validation-for="CenaPoDanu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" onclick="return Validacija()" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-success" asp-action="Index">Vrati se na filmove</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
<script>
    function PrikaziSliku() {
        var File1 = document.getElementById("File1");
        var img1 = document.getElementById("img1");

        var fajl = File1.files[0];

        if (fajl != null && fajl.type.match(/image.*/)) {

            var reader = new FileReader();
            reader.readAsDataURL(fajl);

            reader.onload = function () {

                img1.src = reader.result;
            };

        }
        else {
            img1.src = "";
        }
    }

    function Validacija() {

        var src1 = $("#img1").attr("src");

        if (src1 == "") {
            $("#p1").html("Odaberi sliku");
            return false;
        }
        else {
            return true;
        }
    }
</script>
}

VideoKlub2019/Views/Film/Delete.cshtml
@model VideoKlub2019.Models.Film

@{
    ViewData["Title"] = "Delete";
}


<h3>Da li ste sigurni da zelite da obrisete film?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Naziv
        </dt>
        <dd class="col-sm-10">
            @Model.Naziv
        </dd>
        <dt class="col-sm-2">
            Reziser
        </dt>
        <dd class="col-sm-10">
            @Model.Reziser
        </dd>
        <dt class="col-sm-2">
            Godina
        </dt>
        <dd class="col-sm-10">
            @Model.Godina
        </dd>
        <dt class="col-sm-2">
            CenaPoDanu
        </dt>
        <dd class="col-sm-10">
            @Model.CenaPoDanu
        </dd>
        <dt class="col-sm-2">
            Zanr
        </dt>
        <dd class="col-sm-10">
            @Model.Zanr.NazivZanra
        </dd>
        <div class="col-md-6">
            <img src="/Film/CitajSliku/@Model.FilmId" width="300" height="400" />
        </div>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="FilmId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-success" asp-action="Index">Filmovi</a>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        function PrikaziSliku() {
            var File1 = document.getElementById("File1");
            var img1 = document.getElementById("img1");

            var fajl = File1.files[0];

            if (fajl != null && fajl.type.match(/image.*/)) {

                var reader = new FileReader();
                reader.readAsDataURL(fajl);

                reader.onload = function () {

                    img1.src = reader.result;
                };

            }
            else {
                img1.src = "";
            }
        }

        function Validacija() {

            var src1 = $("#img1").attr("src");

            if (src1 == "") {
                $("#p1").html("Odaberi sliku");
                return false;
            }
            else {
                return true;
            }
        }
    </script>
}

VideoKlub2019/Views/Film/Details.cshtml
@model VideoKlub2019.Models.Film
@inject SignInManager<ApplicationUser> sm
@inject UserManager<ApplicationUser> um
@{
    ViewData["Title"] = "Details";
    var korisnik = await um.GetUserAsync(User);
}

<h3>Detalji o filmu:</h3>

<div>
    <hr style="width:100%; background-color: green;" />
    <dl class="row">
        <div class="col-md-6">
            <dt class="col-sm-2">
                Naziv
            </dt>
            <dd class="col-sm-10">
                @Model.Naziv
            </dd>
            <dt class="col-sm-2">
                Reziser
            </dt>
            <dd class="col-sm-10">
                @Model.Reziser
            </dd>
            <dt class="col-sm-2">
                Godina
            </dt>
            <dd class="col-sm-10">
                @Model.Godina
            </dd>
            @if (sm.IsSignedIn(User) && korisnik.Email == "admin@gmail.com")
            {
                <dt class="col-sm-2">
                    SlikaTip
                </dt>
                <dd class="col-sm-10">
                    @Model.SlikaTip
                </dd>
            }
            <dt class="col-sm-2">
                CenaPoDanu
            </dt>
            <dd class="col-sm-10">
                @Model.CenaPoDanu
            </dd>
            <dt class="col-sm-2">
                Zanr
            </dt>
            <dd class="col-sm-10">
                @Model.Zanr.NazivZanra
            </dd>
        </div>
        <div class="col-md-6">
            <img src="/Film/CitajSliku/@Model.FilmId" width="300" height="400" />
        </div>
    </dl>
</div>
<hr style="width:100%; background-color: green;" />
<div>
    <a asp-controller="Home" class="btn btn-success" asp-action="Index">Vrati se na filmove</a>
    <a asp-action="Index" class="btn btn-success" asp-controller="Komentar" asp-route-id="@Model.FilmId">Vidi komentare</a>
    <a asp-action="Create" class="btn btn-success" asp-controller="Komentar" asp-route-id="@Model.FilmId">Unesi komentar</a>
    @if (sm.IsSignedIn(User) && korisnik.Email == "admin@gmail.com")
    {

        <a asp-action="Edit" class="btn btn-success" asp-route-id="@Model.FilmId">Izmeni film</a>
        <a asp-action="Index" class="btn btn-success">Vrati se na filmove</a>

    }
</div>

VideoKlub2019/Views/Film/Edit.cshtml
@model VideoKlub2019.Models.Film

@{
    ViewData["Title"] = "Edit";
}

    <h3>Izmenite film:</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="FilmId" />
            <input id="promena" type="hidden" name="promena" value="0" />
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZanrId" class="control-label"></label>
                <select asp-for="ZanrId" class="form-control" asp-items="ViewBag.ZanrId"></select>
                <span asp-validation-for="ZanrId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Reziser" class="control-label"></label>
                <input asp-for="Reziser" class="form-control" />
                <span asp-validation-for="Reziser" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Godina" class="control-label"></label>
                <input asp-for="Godina" class="form-control" />
                <span asp-validation-for="Godina" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="File1"></label>
                <input id="File1" type="file" name="odabranaSlika" accept=".jpg, .gif, .png" onchange="PrikaziSliku()" />
            </div>
            <div class="form-group">
                <img id="img1" src="/Film/CitajSliku/@Model.FilmId" width="200" height="150" />
            </div>
            <div class="form-group">
                <label asp-for="CenaPoDanu" class="control-label"></label>
                <input asp-for="CenaPoDanu" class="form-control" />
                <span asp-validation-for="CenaPoDanu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Sacuvaj" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Vidi filmove</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
<script>
    function PrikaziSliku() {
        var File1 = document.getElementById("File1");
        var img1 = document.getElementById("img1");
        var promena = document.getElementById("promena");

        var fajl = File1.files[0];

        if (fajl != null && fajl.type.match(/image.*/)) {

            var reader = new FileReader();
            reader.readAsDataURL(fajl);

            reader.onload = function () {

                img1.src = reader.result;
                promena.setAttribute("value", "1");
            };

        }
        else {
            img1.src = "";
        }
    }

    function Validacija() {

        var src1 = $("#img1").attr("src");

        if (src1 == "") {
            $("#p1").html("Odaberi sliku");
            return false;
        }
        else {
            return true;
        }
    }
</script>
}

VideoKlub2019/Views/Film/Index.cshtml
@model IEnumerable<VideoKlub2019.Models.Film>

@{
    ViewData["Title"] = "Index";
}


<p>
    <a class="btn btn-success" asp-action="Create">Ubaci film</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Naziv
            </th>
            <th>
                Reziser
            </th>
            <th>
                Godina
            </th>
            <th>
                Slika
            </th>
            <th>
               SlikaTip
            </th>
            <th>
                CenaPoDanu
            </th>
            <th>
                Zanr
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.Naziv
            </td>
            <td>
                @item.Reziser
            </td>
            <td>
                @item.Godina
            </td>
            <td>
                <img src="/Film/CitajSliku/@item.FilmId" width="200" height="150" />
            </td>
            <td>
                @item.SlikaTip
            </td>
            <td>
                @item.CenaPoDanu
            </td>
            <td>
                @item.Zanr.NazivZanra
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.FilmId">Promeni</a> |
                <a asp-controller="Iznajmljivanje" asp-action="Create" asp-route-id="@item.FilmId">Iznajmi film</a> |
                <a asp-action="Details" asp-route-id="@item.FilmId">Detalji</a> |
                <a asp-action="Delete" asp-route-id="@item.FilmId">Obrisi</a>
            </td>
        </tr>
}
    </tbody>
</table>