VideoKlub2019/Controllers/FilmController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VideoKlub2019.Models;

namespace VideoKlub2019.Controllers
{
    public class FilmController : Controller
    {
        private readonly VideoKlubContext db;

        public FilmController(VideoKlubContext _db)
        {
            db = _db;
        }

        public FileContentResult CitajSliku(int? id)
        {
            if (id == null)
            {
                return null;
            }
            Film film = db.Filmovi.Find(id);

            if (film == null)
            {
                return null;
            }
            return File(film.Slika, film.SlikaTip);
        }

        [Authorize(Roles = "admin")]
        // GET: Film
        public async Task<IActionResult> Index()
        {
            var videoklub2019Context = db.Filmovi.Include(f => f.Zanr);
            return View(await videoklub2019Context.ToListAsync());
        }

        // GET: Film/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await db.Filmovi
                .Include(f => f.Zanr)
                .FirstOrDefaultAsync(m => m.FilmId == id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        [Authorize(Roles = "admin")]
        // GET: Film/Create
        public IActionResult Create()
        {
            ViewData["ZanrId"] = new SelectList(db.Zanrovi, "ZanrId", "NazivZanra");
            return View();
        }

        // POST: Film/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FilmId,Naziv,ZanrId,Reziser,Godina,Slika,SlikaTip,CenaPoDanu")] Film film, IFormFile odabranaSlika)
        {
            if (ModelState.IsValid)
            {
            using (MemoryStream ms = new MemoryStream())
            {
                await odabranaSlika.CopyToAsync(ms);
                film.Slika = ms.ToArray();
            }
            film.SlikaTip = odabranaSlika.ContentType;
            db.Add(film);
            await db.SaveChangesAsync();

             }
            ViewData["ZanrId"] = new SelectList(db.Zanrovi, "ZanrId", "NazivZanra", film.ZanrId);
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "admin")]
        // GET: Film/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await db.Filmovi.FindAsync(id);
            if (film == null)
            {
                return NotFound();
            }
            ViewData["ZanrId"] = new SelectList(db.Zanrovi, "ZanrId", "NazivZanra", film.ZanrId);
            return View(film);
        }

        // POST: Film/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FilmId,Naziv,ZanrId,Reziser,Godina,Slika,SlikaTip,CenaPoDanu")] Film film, IFormFile odabranaSlika, int promena = 0)
        {
            if (promena == 1 && odabranaSlika == null)
            {
                ModelState.AddModelError("Slika", "Niste odabrali sliku");
            }
            if (id != film.FilmId)
            {
                return NotFound();
            }
            Film fl = db.Filmovi.Find(film.FilmId);

            if (promena == 1)
            {
                using (MemoryStream ms = new MemoryStream())
                {
                    await odabranaSlika.CopyToAsync(ms);
                    fl.Slika = ms.ToArray();
                }
                fl.SlikaTip = odabranaSlika.ContentType;
            }
            fl.Naziv = film.Naziv;
            fl.ZanrId = film.ZanrId;
            fl.Reziser = film.Reziser;
            fl.Godina = film.Godina;
            fl.CenaPoDanu = film.CenaPoDanu;
            if (ModelState.IsValid)
            {
            try
            {
                db.Update(fl);
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!FilmExists(fl.FilmId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            }
            ViewData["ZanrId"] = new SelectList(db.Zanrovi, "ZanrId", "NazivZanra", film.ZanrId);
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "admin")]
        // GET: Film/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await db.Filmovi
                .Include(f => f.Zanr)
                .FirstOrDefaultAsync(m => m.FilmId == id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        // POST: Film/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var film = await db.Filmovi.FindAsync(id);
            db.Filmovi.Remove(film);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FilmExists(int id)
        {
            return db.Filmovi.Any(e => e.FilmId == id);
        }
    }
}

VideoKlub2019/Controllers/IznajmljivanjeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VideoKlub2019.Models;

namespace VideoKlub2019.Controllers
{
    public class IznajmljivanjeController : Controller
    {
        private readonly VideoKlubContext db;

        public IznajmljivanjeController(VideoKlubContext _db)
        {
            db = _db;
        }

        [Authorize(Roles = "admin")]
        // GET: Iznajmljivanje
        public async Task<IActionResult> Index()
        {
            var videoklub2019Context = db.Iznajmljivanja.Include(i => i.Film);
            return View(await videoklub2019Context.ToListAsync());
        }

        // GET: Iznajmljivanje/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var iznajmljivanje = await db.Iznajmljivanja
                .Include(i => i.Film)
                .FirstOrDefaultAsync(m => m.IznajmljivanjeId == id);
            if (iznajmljivanje == null)
            {
                return NotFound();
            }

            return View(iznajmljivanje);
        }

        [Authorize]
        // GET: Iznajmljivanje/Create
        public IActionResult Create()
        {
            ViewData["FilmId"] = new SelectList(db.Filmovi, "FilmId", "Naziv");
            return View();
        }

        // POST: Iznajmljivanje/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IznajmljivanjeId,FilmId,ClanId,DatumIznajmljivanja,DatumVracanja")] Iznajmljivanje iznajmljivanje)
        {
            if (ModelState.IsValid)
            {
                db.Add(iznajmljivanje);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FilmId"] = new SelectList(db.Filmovi, "FilmId", "Naziv", iznajmljivanje.FilmId);
            return View(iznajmljivanje);
        }

        [Authorize(Roles = "admin")]
        // GET: Iznajmljivanje/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var iznajmljivanje = await db.Iznajmljivanja.FindAsync(id);
            if (iznajmljivanje == null)
            {
                return NotFound();
            }
            ViewData["FilmId"] = new SelectList(db.Filmovi, "FilmId", "Naziv", iznajmljivanje.FilmId);
            return View(iznajmljivanje);
        }

        // POST: Iznajmljivanje/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IznajmljivanjeId,FilmId,ClanId,DatumIznajmljivanja,DatumVracanja")] Iznajmljivanje iznajmljivanje)
        {
            if (id != iznajmljivanje.IznajmljivanjeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(iznajmljivanje);
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IznajmljivanjeExists(iznajmljivanje.IznajmljivanjeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FilmId"] = new SelectList(db.Filmovi, "FilmId", "Naziv", iznajmljivanje.FilmId);
            return View(iznajmljivanje);
        }

        [Authorize(Roles = "admin")]
        // GET: Iznajmljivanje/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var iznajmljivanje = await db.Iznajmljivanja
                .Include(i => i.Film)
                .FirstOrDefaultAsync(m => m.IznajmljivanjeId == id);
            if (iznajmljivanje == null)
            {
                return NotFound();
            }

            return View(iznajmljivanje);
        }

        // POST: Iznajmljivanje/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var iznajmljivanje = await db.Iznajmljivanja.FindAsync(id);
            db.Iznajmljivanja.Remove(iznajmljivanje);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool IznajmljivanjeExists(int id)
        {
            return db.Iznajmljivanja.Any(e => e.IznajmljivanjeId == id);
        }
    }
}

VideoKlub2019/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> sm
@inject UserManager<ApplicationUser> um
@{ 
    var korisnik = await um.GetUserAsync(User);
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VideoKlub2019</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css?family=Allan" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cardo" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" type="text/css" rel="stylesheet">
    @RenderSection("Styles", required: false)
</head>
<body style="background-color: #b5b5b5 !important;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark box-shadow mb-3" style="font-family: 'Allan', Helvetica, Arial, sans-serif; font-size: 22px; background-color: #3d3d3d !important;">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/LOGO.png" width="40" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Pocetna</a>
                        </li>
                        <li class="nav-item">
                            @if (sm.IsSignedIn(User) && korisnik.Email == "admin@gmail.com")
                            {
                                <a class="nav-link text-light" asp-area="" asp-controller="Film" asp-action="Index">Filmovi</a>

                            }
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Posalji">Kontakt</a>
                        </li>
                        <li class="nav-item">
                            @if (sm.IsSignedIn(User) && korisnik.Email == "admin@gmail.com")
                            {
                                <a class="nav-link text-light" asp-area="" asp-controller="Iznajmljivanje" asp-action="Index">Iznajmljivanja</a>
                            }
                        </li>
                    </ul>
                </div>

            </div>
        </nav>
    </header>
    <div class="container">

        <main role="main" class="pb-3">
            @RenderBody()
        </main>

    </div>

    <footer class="footer" style="background-color:  #3d3d3d !important; border-top: 2px solid #20a116; height: 70px;">
        <div class="container" style="padding: 10px 0px 0px 0px; height: 70px;">
            <center><img src="~/images/LOGO.png" width="40" /></center>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>